networks:
  pg-network:
    name: pg-network
    driver: bridge
services:
  pg-database:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./volumes/ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    networks:
      - pg-network
  pg-admin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    user: '$UID:$GID'
    volumes:
      - "./volumes/data_pgadmin:/var/lib/pgadmin"
    ports:
      - "8080:80"
    networks:
      - pg-network